import configparser


# CONFIG
config = configparser.ConfigParser()
config.read('dwh.cfg')

# DROP TABLES

staging_events_table_drop = "drop table if exists staging_events;"
staging_songs_table_drop = "drop table if exists staging_songs;"
songplay_table_drop = "drop table if exists songplays;"
user_table_drop = "drop table if exists users;"
song_table_drop = "drop table if exists songs;"
artist_table_drop = "drop table if exists artists;"
time_table_drop = "drop table if exists time;"

# CREATE TABLES

staging_events_table_create= ("""create table if not exists staging_events (
    artist          text,
    auth            text,
    first_name      text,
    gender          text,
    item_in_session int,
    last_name       text,
    length          numeric,
    level           text,
    location        text,
    method          text,
    page            text,
    registration    bigint,
    session_id      int,
    song            text,
    status          int,
    ts              bigint,
    user_agent      text,
    user_id         int
)
diststyle even;
""")

staging_songs_table_create = ("""create table if not exists staging_songs (
    num_songs       int,
    artist_id       text,
    latitude        numeric,
    longitude       numeric,
    artist_location text,
    artist_name     text,
    song_id         text,
    title           text,
    duration        numeric,
    year            int
)
diststyle even;
""")

songplay_table_create = ("""create table if not exists songplays (
    songplay_id int       not null generated by default as identity (0, 1) primary key,
    start_time  timestamp not null,
    user_id     text      not null,
    level       text,
    song_id     text,
    artist_id   text,
    session_id  text,
    location    text,
    user_agent  text
)
diststyle even
sortkey (user_id, song_id, artist_id);
""")

user_table_create = ("""create table if not exists users (
    user_id    text not null distkey primary key,
    first_name text,
    last_name  text,
    gender     text,
    level      text
)
diststyle key;
""")

song_table_create = ("""create table if not exists songs (
    song_id   text not null distkey primary key,
    title     text,
    artist_id text sortkey,
    year      int,
    duration  numeric
)
diststyle key;
""")

artist_table_create = ("""create table if not exists artists (
    artist_id text not null distkey primary key,
    name      text,
    location  text,
    latitude numeric,
    longitude numeric
)
diststyle key;
""")

time_table_create = ("""create table if not exists time (
    start_time timestamp not null distkey sortkey primary key,
    hour       int,
    day        int,
    week       int,
    month      int,
    year       int,
    weekday    int
)
diststyle key;
""")

# STAGING TABLES

ARN = config.get("IAM_ROLE", "ARN")

LOG_DATA = config.get("S3", "LOG_DATA")
LOG_PATH = config.get("S3", "LOG_JSONPATH")
staging_events_copy = ("""copy staging_events
from {}
iam_role {}
region 'us-west-2'
json {}
""").format(LOG_DATA, ARN, LOG_PATH)

SONG_DATA = config.get("S3", "SONG_DATA")
staging_songs_copy = ("""copy staging_songs
from {}
iam_role {}
region 'us-west-2'
json 'auto'
""").format(SONG_DATA, ARN)

# FINAL TABLES

songplay_table_insert = ("""insert into songplays
(start_time, user_id, level, song_id, artist_id, session_id, location, user_agent)
select
    timestamp 'epoch' + e.ts / 1000 * interval '1 second',
    e.user_id,
    e.level,
    s.song_id,
    s.artist_id,
    e.session_id,
    e.location,
    e.user_agent
from
    staging_events e
join
    staging_songs s
    on
        e.artist = s.artist_name
        and e.song = s.title
        and e.length = s.duration
where
    e.page like 'NextSong'
    and e.ts is not null
    and e.user_id is not null
""")

user_table_insert = ("""insert into users
(user_id, first_name, last_name, gender, level)
select
    user_id,
    first_name,
    last_name,
    gender,
    level
from (
    select
        distinct user_id,
        first_name,
        last_name,
        gender,
        level,
        row_number() over (partition by user_id order by ts desc) rn
    from
        staging_events e
    where
        user_id is not null
    ) t
where
    rn = 1
""")

song_table_insert = ("""insert into songs
(song_id, title, artist_id, year, duration)
select
    distinct song_id,
    title,
    artist_id,
    year,
    duration
from
    staging_songs s
where
    song_id is not null
""")

artist_table_insert = ("""insert into artists
(artist_id, name, location, latitude, longitude)
select
    distinct artist_id,
    artist_name,
    artist_location,
    latitude,
    longitude
from
    staging_songs s
where
    s.artist_id is not null
""")

time_table_insert = ("""insert into time
(start_time, hour, day, week, month, year, weekday)
select
    start_time,
    extract(h from start_time),
    extract(d from start_time),
    extract(w from start_time),
    extract(mon from start_time),
    extract(y from start_time),
    extract(dw from start_time)
from (
    select
        timestamp 'epoch' + ts / 1000 * interval '1 second' start_time
    from
        staging_events
    where
        start_time is not null
    ) t
;
""")

# check the created tables

check_events_songs_join = ("""select
    distinct e.artist, e.song, e.length, e.first_name, e.last_name
from staging_events e
join staging_songs s
    on e.artist = s.artist_name
    and e.song = s.title
    and e.length = s.duration
limit 4;
""")

check_songplays_1 = ("select * from songplays limit 3")

check_songplays_2 = ("""select
    count(1),
    count(distinct songplay_id),
    count(distinct user_id),
    count(distinct song_id),
    count(distinct artist_id)
from songplays;
""")

check_songplays_3 = ("""select
    distinct songplay_id,
    p.user_id,
    first_name,
    last_name,
    p.song_id,
    title,
    p.artist_id,
    name
from songplays p
join users u
    on p.user_id = u.user_id
join songs s
    on p.song_id = s.song_id
join artists a
    on p.artist_id = a.artist_id
limit 4;
""")

check_users = ("""select
    count(1),
    count(distinct user_id)
from users;
""")

check_songs = ("""select
    count(1),
    count(distinct song_id)
from songs;
""")

check_artists = ("""select
    count(1),
    count(distinct artist_id)
from artists;
""")

check_time = ("""select *
from time limit 4""")

# QUERY LISTS

create_table_queries = [staging_events_table_create, staging_songs_table_create, songplay_table_create, user_table_create, song_table_create, artist_table_create, time_table_create]
drop_table_queries = [staging_events_table_drop, staging_songs_table_drop, songplay_table_drop, user_table_drop, song_table_drop, artist_table_drop, time_table_drop]
copy_table_queries = [staging_events_copy, staging_songs_copy]
insert_table_queries = [songplay_table_insert, user_table_insert, song_table_insert, artist_table_insert, time_table_insert]
check_table_queries = [
    check_events_songs_join,
    check_songplays_1,
    check_songplays_2,
    check_songplays_3,
    check_users,
    check_songs,
    check_artists,
    check_time]
