version: "3.7"
services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=airflow
            - MYSQL_PASSWORD=airflow
            - MYSQL_DATABASE=airflow
        volumes:
            - ./my.cnf:/etc/mysql/conf.d/my.cnf:ro
        ports:
            - "3306:3306"
    airflow:
        build: .
        image: airflow
        container_name: airflow
        depends_on:
            - mysql
        environment:
            - AIRFLOW_HOME=/home/workspace/airflow
            - AIRFLOW__CORE__LOAD_EXAMPLES=False
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql+mysqldb://airflow:airflow@mysql:3306/airflow
            - AIRFLOW__WEBSERVER__WORKERS=2
            - MYSQL_PORT=3306
            - MYSQL_HOST=mysql
        env_file:
            - ./.env
        ports:
            - "8080:8080"
        volumes:
            - ./dags:/home/workspace/airflow/dags
            - ./plugins:/home/workspace/airflow/plugins
            - ./create_tables.sql:/home/workspace/airflow/create_tables.sql
        command: webserver
        stdin_open: true
        tty: true
